### ISSUE TITLE
Please fix metadata

### ISSUE THREAD

**Issue by pcav** [abocianowski/QRectangleCreator#1]
code repo is wrong, home page should be informative about the plugin (the same address as the repo would do).
Thanks.

**Comment by abocianowski** [comment]
I changed the homepage address to github. I hope it will be ok. Regards

**Comment by pcav** [comment]
Apparently still the same: http://plugins.qgis.org/plugins/QRectangleCreator/

**Comment by abocianowski** [comment]
I do not understand. I changed the website address from: gishelper.pl to gitub ...

**Comment by abocianowski** [comment]
I checked another recently published plugin "Bezier Editing". The link to the home page looks similar.
![image](https://user-images.githubusercontent.com/50774139/58114276-be382580-7bf7-11e9-90c5-5ac445c64e73.png)
![image](https://user-images.githubusercontent.com/50774139/58114284-c2644300-7bf7-11e9-9333-26050f416551.png)

**Comment by pcav** [comment]
I mean the code repo: https://github.com/abocianowski/QRectangleCreatorchangelog=version=0.1%20-%20plugin%20create
home page is OK

**Comment by abocianowski** [comment]
In metadata.txt its ok. Please look at this:
![image](https://user-images.githubusercontent.com/50774139/58115969-80d59700-7bfb-11e9-992b-9a56dd88ccf7.png)
https://github.com/abocianowski/QRectangleCreator/blob/master/metadata.txt


The address change takes place during the import of the plugin from the zip archive.
![image](https://user-images.githubusercontent.com/50774139/58116037-abbfeb00-7bfb-11e9-9d87-043059383442.png)

I changed this manually at https://plugins.qgis.org/plugins/QRectangleCreator/
