### ISSUE TITLE
Settings max value

### ISSUE THREAD

**Issue by jmsoeiro** [abocianowski/QRectangleCreator#2]
The settings interface doesn't allow for width or height values larger than 10000 map units.
If you have somewhat small units (meters ...), that limit is to low.
Good work!

**Comment by abocianowski** [comment]
Hi, thank you for reporting. I've updated the maximum value to 999999999. The changes are in the repository. The new version of the plugin is 0.3 waiting for acceptance in the Qgis repository. Check back soon (maybe tomorrow) or is available for download now.
https://plugins.qgis.org/plugins/QRectangleCreator/
![image](https://user-images.githubusercontent.com/50774139/58194546-1b021180-7cc6-11e9-9936-aa19dd4fc0be.png)
